### ISSUE TITLE
Review from Krishna

### ISSUE THREAD

**Issue by benjaminmodayil** [benjaminmodayil/Coffee-Quiz-Application#1]
Before I send it out, can I get a review?
Note other issue with Smoothscroll.

**Comment by krokhale** [comment]
Sorry it took me this long!

So just looked through your code:

- The UI looks great, i think it's the best implementation of this app that i have seen yet.
- The ES6 class structure is neat and modular, might be an overkill at this point with the scope of the app, but super useful to show around your skills.
- Something that struck me, was maybe you could have animations to transition into and out of questions, and correct and incorrect answers with a shake or something.

Look up this library.

https://daneden.github.io/animate.css/

Otherwise looks neat!
